version: 1.0.{build}
image: Visual Studio 2019

cache:
  - "..\\.yarn-cache"

install:
  - ps: "choco install nodejs-lts --version=$($(Get-Content .nvmrc).replace('v',''))"
  - npm i -g yarn
  - node --version
  - yarn --version

build_script:
  - yarn install --nonInteractive --frozen-lockfile --preferred-cache-folder ..\\.yarn-cache
  - yarn build

test_script:
  - docker version
  - ps: "& 'C:/Program Files/Docker/Docker/DockerCli.exe' -SwitchDaemon -SwitchLinuxEngine"
  - yarn test:ci