version: 1.0.{build}
image: Visual Studio 2019

install:
  - docker version

build: off

test_script:
  - ps: "& 'C:/Program Files/Docker/Docker/DockerCli.exe' -SwitchDaemon -SwitchLinuxEngine"
  - choco install nodejs-lts --version=14.16.0
  - npm i -g yarn
  - yarn install --nonInteractive --frozen-lockfile
  - yarn build
  - yarn test:ci