version: 1.0.{build}
image: Visual Studio 2019

cache:
  - "..\\.yarn-cache"

install:
  - ps: "Install-Product node (Get-Content ./.nvmrc) x64"
  # - choco install nodejs-lts --version=14.16.0
  - npm i -g yarn
  - node --version
  - yarn --version

build_script:
  - yarn install --nonInteractive --frozen-lockfile --preferred-cache-folder ..\\.yarn-cache
  - yarn build

test_script:
  - docker version
  - docker-compose version
  - ps: "& 'C:/Program Files/Docker/Docker/DockerCli.exe' -SwitchDaemon -SwitchLinuxEngine"
  - yarn test:ci