version: 1.0.{build}
image: Visual Studio 2019

install:
  - docker version
  - docker-compose version
  - choco install nodejs-lts --version=14.16.0
  - npm i -g yarn

build: off

test_script:
  - ps: "& 'C:/Program Files/Docker/Docker/DockerCli.exe' -SwitchDaemon -SwitchLinuxEngine"
  - yarn install --nonInteractive --frozen-lockfile
  - yarn build
  - yarn test:ci