version: '3'
services:
  eth-testnet:
    image: 'trufflesuite/ganache-cli:v6.12.2'
    ports:
      - '${ETH_TESTNET_PORT}:8545'
    command: -l 8000000 --networkId 1576478390085 --deterministic --hostname=0.0.0.0
