version: '3'
services:
  dev-server:
    build: ./
    ports:
      - '${DEV_SERVER_PORT}:${DEV_SERVER_PORT}'
    links:
      - ganache
    environment:
      ganache: 'ganache:${ETHEREUM_PORT}'
  ganache:
    image: 'trufflesuite/ganache-cli'
    ports:
      - '${ETHEREUM_PORT}:8545'
    command: -l 8000000 --networkId 1576478390085 --deterministic --hostname=0.0.0.0
  ipfs:
    image: 'ipfs/go-ipfs:v0.4.23'
    ports:
      - '${IPFS_PORT}:5001'
  graph-node:
    image: graphprotocol/graph-node:v0.18.0
    ports:
      - '${SUBGRAPH_PORT}:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    links:
      - ipfs
      - postgres
      - ganache
    environment:
      postgres_host: postgres:5432
      postgres_user: postgres
      postgres_pass: letmein
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      ethereum: 'private:http://ganache:8545'
      GRAPH_IPFS_TIMEOUT: '2'
      GRAPH_MAX_IPFS_FILE_BYTES: '400000'
      GRAPH_GRAPHQL_MAX_FIRST: '1000'
      RUST_LOG: info
      RUST_BACKTRACE: 1
  postgres:
    build: postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: letmein
