format: "0.2.0"
jobs:
  fs_to_ens:
    config:
      provider: 'http://localhost:8545'
      ensRegistryAddress: $ENS_REG_ADDR
      ensRegistrarAddress: $ENS_REGISTRAR_ADDR
      ensResolverAddress: $ENS_RESOLVER_ADDR
      gatewayUri: $IPFS_GATEWAY_URI
    steps:
      - name: ens_register
        package: ens-recursive-name-register
        uri: wrap://ens/foo.eth
      - name: ipfs_deploy
        package: ipfs
        uri: wrap://fs/./build
      - name: from_deploy
        package: ens
        uri: $$ipfs_deploy
        config:
          domainName: foo.eth